#define ZMQ_SOCK_MSG_IN "ipc:///tmp/sepm_msg_in"
#define ZMQ_SOCK_MSG_IN_BIND ZMQ_SOCK_MSG_IN
#define ZMQ_SOCK_MSG_IN_CONN ZMQ_SOCK_MSG_IN

#define ZMQ_SOCK_CHAN_ACTION "ipc:///tmp/sepm_chan_action"
#define ZMQ_SOCK_CHAN_ACTION_BIND ZMQ_SOCK_CHAN_ACTION
#define ZMQ_SOCK_CHAN_ACTION_CONN ZMQ_SOCK_CHAN_ACTION

#define ZMQ_SOCK_CHAN_EVENT "ipc://sepm_chan_event"
#define ZMQ_SOCK_CHAN_EVENT_BIND ZMQ_SOCK_CHAN_EVENT
#define ZMQ_SOCK_CHAN_EVENT_CONN ZMQ_SOCK_CHAN_EVENT

#define ZMQ_SOCK_MSG_OUT "ipc:///tmp/sepm_msg_out"
#define ZMQ_SOCK_MSG_OUT_BIND ZMQ_SOCK_MSG_OUT
#define ZMQ_SOCK_MSG_OUT_CONN ZMQ_SOCK_MSG_OUT
